#!/usr/bin/env python3
"""Generate dizi's powerhint.json variants from the pre-fix config.

The pre-fix config (LineageOS garnet's, generated by qcom-perf-parser) maps perf-HAL
cluster 0 onto CPUs 0-3, but on parrot cluster 0 is the big cluster: stock's 120 fps
touch boost 0x1080 asks cluster 0 for 2208 MHz (the A55s top out at 1958 MHz), and
stock powerhint.xml labels cluster 1 "L CPU". So every per-cluster value landed on the
wrong cores.

Usage: powerhint-variants.py <pre-fix powerhint.json> <out dir>

Writes:
  powerhint-old.json     the input, unchanged (A/B baseline)
  powerhint.json         cluster fix with stock values (the default)
  powerhint-trim.json    cluster fix, gold touch floor 1804800 instead of 2208000
  powerhint-launch.json  cluster fix + LAUNCH: cpu_dma_latency, GPU no-nap, UFS clock
                         gating off, DDR floor (CLO parrot / stock 0x1081, Qualcomm Pixels)
  powerhint-frame.json   cluster fix + CPU_LOAD_RESET (GPU/DDR floor on the first frame
                         after idle) + DISPLAY_UPDATE_IMMINENT (hold the cpufreq down-rate)

Select one at runtime (userdebug, as root):
  setprop vendor.powerhal.config powerhint-trim.json
  stop vendor.power-hal-aidl; start vendor.power-hal-aidl
"""

import copy
import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

Json = dict[str, Any]

SILVER = range(0, 4)
GOLD = range(4, 8)

MIN_FREQ = "sysKernelMsmPerformanceParametersCpuMinFreq"
MAX_FREQ = "sysKernelMsmPerformanceParametersCpuMaxFreq"
CORE_CTL_CPU0 = "sysDevicesSystemCpuCpu0CoreCtlMinCpus"
CORE_CTL_GOLD = "sysDevicesSystemCpuCpu4CoreCtlMinCpus"
HISPEED_FREQ_OLD = "sysDevicesSystemCpuCpu4CpufreqWaltHispeedFreq"
HISPEED_LOAD_OLD = "sysDevicesSystemCpuCpu4CpufreqWaltHispeedLoad"
HISPEED_FREQ = "sysDevicesSystemCpuCpufreqPolicy0WaltHispeedFreq"
HISPEED_LOAD = "sysDevicesSystemCpuCpufreqPolicy0WaltHispeedLoad"
LOAD_BOOST = ("sysDevicesSystemCpuCpufreqPolicy4WaltBoost",
              "sysDevicesSystemCpuCpufreqPolicy0WaltBoost")
GPU_MIN = "sysClassKgslKgsl3d0DevfreqMinFreq"
GPU_MIN_PWRLEVEL = "sysClassKgslKgsl3d0MinPwrlevel"
DDR_MIN = "sysDevicesSystemCpuBusDcvsDdr19091000QcomBwmonDdrMinFreq"
CAMERA = ("CAMERA_STREAMING_LOW", "CAMERA_STREAMING_MID", "CAMERA_STREAMING_HIGH")


def freqs(cpus: range, khz: int) -> str:
    return " ".join(f"{cpu}:{khz}" for cpu in cpus)


def both(silver: int, gold: int) -> str:
    return f"{freqs(SILVER, silver)} {freqs(GOLD, gold)}"


class Config:
    """A powerhint.json being edited."""

    def __init__(self, j: Json) -> None:
        self.j = j

    def node(self, name: str) -> Json:
        for n in self.j["Nodes"]:
            if n["Name"] == name:
                return n
        raise KeyError(name)

    def add_node(self, node: Json) -> None:
        self.j["Nodes"].append(node)

    def remove_node(self, name: str) -> None:
        self.j["Nodes"].remove(self.node(name))

    def add_value(self, name: str, value: str) -> None:
        values = self.node(name)["Values"]
        if value not in values:
            values.append(value)

    def actions(self, hint: str, node: str) -> list[Json]:
        return [a for a in self.j["Actions"] if a["PowerHint"] == hint and a.get("Node") == node]

    def set_value(self, action: Json, value: str, node: str | None = None) -> None:
        """Point the action at value. libperfmgr ranks a node's Values by position (the
        lowest index among active requests wins), so on the same node the new value takes
        the old one's place."""
        if node is not None:
            action["Node"] = node
            self.add_value(node, value)
        else:
            values = self.node(action["Node"])["Values"]
            if value not in values:
                values.insert(values.index(action["Value"]) + 1, value)
        action["Value"] = value

    def add_action(self, hint: str, node: str, value: str, duration: int) -> None:
        self.add_value(node, value)
        self.j["Actions"].append({"PowerHint": hint, "Node": node, "Value": value, "Duration": duration})

    def drop_unused_values(self) -> None:
        used: dict[str, set[str]] = {}
        for a in self.j["Actions"]:
            if "Node" in a:
                used.setdefault(a["Node"], set()).add(a["Value"])
        for n in self.j["Nodes"]:
            default = n["Values"][n.get("DefaultIndex", 0)]
            n["Values"] = [v for v in n["Values"] if v == default or v in used.get(n["Name"], set())]
            if "DefaultIndex" in n:
                n["DefaultIndex"] = n["Values"].index(default)


def cluster_fix(c: Config, gold_touch_khz: int) -> None:
    # Touch (stock 0x1080 at 120 fps): gold min 2208, silver min 1497, 3 golds online.
    for a in c.actions("INTERACTION", MIN_FREQ):
        c.set_value(a, both(1497600, gold_touch_khz))

    # core_ctl: post_boot disables it on the silvers and runs the golds with min_cpus 2.
    c.add_node({"Name": CORE_CTL_GOLD, "Path": "/sys/devices/system/cpu/cpu4/core_ctl/min_cpus",
                "Values": ["2"], "DefaultIndex": 0, "ResetOnInit": True})
    for hint in ("INTERACTION", *CAMERA):
        for a in c.actions(hint, CORE_CTL_CPU0):
            c.set_value(a, a["Value"], CORE_CTL_GOLD)
    c.remove_node(CORE_CTL_CPU0)

    # Camera (stock powerhint.xml): "L CPU Min Freq 940Mhz, Max Freq 1.5Ghz", "L CPU
    # Hispeed freq of 940Mhz", "L CPU - Set hispeed load 95", sched load boost -10.
    c.add_node({"Name": HISPEED_FREQ, "Path": "/sys/devices/system/cpu/cpufreq/policy0/walt/hispeed_freq",
                "Values": ["1110000"], "DefaultIndex": 0, "ResetOnInit": True})
    c.add_node({"Name": HISPEED_LOAD, "Path": "/sys/devices/system/cpu/cpufreq/policy0/walt/hispeed_load",
                "Values": ["85"], "DefaultIndex": 0, "ResetOnInit": True})
    for hint in CAMERA:
        for a in c.actions(hint, MAX_FREQ):
            if a["Value"] == freqs(GOLD, 1497600):
                c.set_value(a, freqs(SILVER, 1497600))
        for a in c.actions(hint, MIN_FREQ):
            if a["Value"] == freqs(GOLD, 960000):
                c.set_value(a, freqs(SILVER, 960000))
        for node in LOAD_BOOST:
            for a in c.actions(hint, node):
                c.set_value(a, "-10")
        for a in c.actions(hint, HISPEED_FREQ_OLD):
            c.set_value(a, "940800", HISPEED_FREQ)
        for a in c.actions(hint, HISPEED_LOAD_OLD):
            c.set_value(a, a["Value"], HISPEED_LOAD)
    c.remove_node(HISPEED_FREQ_OLD)
    c.remove_node(HISPEED_LOAD_OLD)


def launch(c: Config) -> None:
    # CLO parrot / stock 0x1081 and Qualcomm Pixels (redbull ece4027: 5-20% faster cold
    # launches from the UFS part alone). LAUNCH lasts at most 2 s; the framework ends it
    # once the app has drawn.
    c.add_action("LAUNCH", "devCpuDmaLatency", "1", 2000)
    c.add_node({"Name": "sysClassKgslKgsl3d0ForceNoNap", "Path": "/sys/class/kgsl/kgsl-3d0/force_no_nap",
                "Values": ["0"], "DefaultIndex": 0, "ResetOnInit": True})
    c.add_action("LAUNCH", "sysClassKgslKgsl3d0ForceNoNap", "1", 2000)
    # init.qcom.rc turns clock gating off during boot and back on at boot_completed, so
    # leave the node alone when the HAL starts.
    c.add_node({"Name": "sysDevicesPlatformSoc1d84000UfshcClkgateEnable",
                "Path": "/sys/devices/platform/soc/1d84000.ufshc/clkgate_enable",
                "Values": ["1"], "DefaultIndex": 0, "ResetOnInit": False})
    c.add_action("LAUNCH", "sysDevicesPlatformSoc1d84000UfshcClkgateEnable", "0", 2000)
    c.add_action("LAUNCH", DDR_MIN, "1555000", 2000)


def frame(c: Config) -> None:
    # Pixel caiman/tangorpro: floor the GPU and DDR for the first frame after idle
    # (HWUI sends CPU_LOAD_RESET after 100 ms idle; SF after 80 ms, with ADPF on).
    c.add_action("CPU_LOAD_RESET", GPU_MIN, "600000000", 50)
    c.add_action("CPU_LOAD_RESET", DDR_MIN, "1555000", 33)
    # SF sends DISPLAY_UPDATE_IMMINENT when it wakes from idle. Pixel holds the cpufreq
    # down-rate limit for 50 ms so frequency doesn't drop between the first frames.
    for policy, us in ((0, "5000"), (4, "20000"), (7, "20000")):
        name = f"sysDevicesSystemCpuCpufreqPolicy{policy}WaltDownRateLimitUs"
        c.add_node({"Name": name, "Path": f"/sys/devices/system/cpu/cpufreq/policy{policy}/walt/down_rate_limit_us",
                    "Values": ["0"], "DefaultIndex": 0, "ResetOnInit": True})
        c.add_action("DISPLAY_UPDATE_IMMINENT", name, us, 50)


def gpu_pwrlevel(c: Config) -> None:
    # kgsl's devfreq min_freq floors don't hold on this kernel (the governor drops below them);
    # min_pwrlevel does (0 = 940 MHz ... 8 = 295 MHz). Values in priority order: 940 beats 600.
    # EXPENSIVE_RENDERING: SF composing on the GPU (ro.sf.gpu_composition_boost); LAUNCH covers the
    # first frames of a transition, before SF's hint arrives. INTERACTION gets the 600 MHz its
    # devfreq floor always meant.
    c.add_node({"Name": GPU_MIN_PWRLEVEL, "Path": "/sys/class/kgsl/kgsl-3d0/min_pwrlevel",
                "Values": ["0", "5", "8"], "DefaultIndex": 2, "ResetOnInit": True})
    c.add_action("EXPENSIVE_RENDERING", GPU_MIN_PWRLEVEL, "0", 0)
    c.add_action("LAUNCH", GPU_MIN_PWRLEVEL, "0", 0)
    c.add_action("INTERACTION", GPU_MIN_PWRLEVEL, "5", 0)


def stock_sched(c: Config) -> None:
    # Stock's 120 Hz boost (0x109B) keeps these at 0 all the time; the rest of that set is in
    # init.dizi.rc. Measured on cnb-release-4: Recents launcher jank ~2.6 -> ~2.1 %.
    for name in ("procSysWaltSchedMinTaskUtilForColocation", "procSysWaltSchedMinTaskUtilForBoost"):
        node = c.node(name)
        if "0" not in node["Values"]:
            node["Values"].append("0")
        node["DefaultIndex"] = node["Values"].index("0")
        # post_boot leaves 35/51 there; write the default when the HAL starts, not only after a hint.
        node["ResetOnInit"] = True


def make(old: Json, gold_touch_khz: int = 2208000, extra: Callable[[Config], None] | None = None) -> Json:
    c = Config(copy.deepcopy(old))
    cluster_fix(c, gold_touch_khz)
    gpu_pwrlevel(c)
    stock_sched(c)
    if extra is not None:
        extra(c)
    c.drop_unused_values()
    return c.j


def validate(j: Json, name: str) -> None:
    nodes = {n["Name"]: n for n in j["Nodes"]}
    if len(nodes) != len(j["Nodes"]):
        raise ValueError(f"{name}: duplicate node")
    paths = [n["Path"] for n in j["Nodes"]]
    if len(set(paths)) != len(paths):
        raise ValueError(f"{name}: duplicate path")
    for a in j["Actions"]:
        if "Node" not in a:
            continue
        n = nodes.get(a["Node"])
        if n is None:
            raise ValueError(f"{name}: {a['PowerHint']} uses missing node {a['Node']}")
        if a["Value"] not in n["Values"]:
            raise ValueError(f"{name}: {a['PowerHint']} {a['Node']}={a['Value']} not in Values")
    for n in j["Nodes"]:
        if not 0 <= n.get("DefaultIndex", 0) < len(n["Values"]):
            raise ValueError(f"{name}: {n['Name']} DefaultIndex out of range")


def main() -> None:
    src, out = Path(sys.argv[1]), Path(sys.argv[2])
    old = json.loads(src.read_text())
    variants = {
        "powerhint-old.json": copy.deepcopy(old),
        "powerhint.json": make(old),
        "powerhint-trim.json": make(old, 1804800),
        "powerhint-launch.json": make(old, extra=launch),
        "powerhint-frame.json": make(old, extra=frame),
    }
    out.mkdir(parents=True, exist_ok=True)
    for name, j in variants.items():
        validate(j, name)
        (out / name).write_text(json.dumps(j, indent=4) + "\n")
        print(name)


if __name__ == "__main__":
    main()
